name: Base
logging: True
unlabeled: True

model:
    pretrained: True

data:
    path: /home/cv_defect/YASIN/edge_correction_ignc/data/manufacturing_128_yasin
    num_classes: 7

param:
    lr: 1e-5
    batch_size: 128

trainer:
    max_steps: 100_000
    check_val_every_n_epoch: 1

backbone:
    type: swin

logger:
    project: cv_defect_manufacturing